from typing import List, Dict

BOOK_TEMPLATES = [
    {
        "id": "space-adventures",
        "title": "My Space Adventure",
        "description": "Travel across the galaxy and meet friendly aliens!",
        "age_group": "5-8",
        "emoji": "🚀",
        "color": "#4338ca",
        "pages": [
            {"page_number": 1, "text": "My Space Adventure", "image_prompt": "A magnificent book cover: a brave child astronaut standing on a small planet, looking out at a swirling galaxy of purple, blue and gold. The title 'My Space Adventure' is written in golden glowing letters across the sky.", "base_image_path": "/defaults/space-adventures/page-1.png"},
            {"page_number": 2, "text": "Once upon a time, a brave astronaut named [HERO] looked at the stars from their bedroom window. The night sky was filled with twinkling lights, and [HERO] dreamed of visiting every single one. They had a special telescope that could see all the way to the edge of the galaxy.", "image_prompt": "Cute child astronaut in a cosmic-themed bedroom, looking through a glowing telescope at a starry night sky, children's book style, whimsical and magical.", "base_image_path": "/defaults/space-adventures/page-2.png"},
            {"page_number": 3, "text": "Suddenly, a tiny, glowing rocket landed softly on their desk with a gentle 'ping'. [HERO] was wide awake and ready for an adventure! The rocket was painted bright silver and had a tiny door that looked just like the entrance to a secret world.", "image_prompt": "Child eyes wide with wonder, looking at a tiny, glowing silver rocket ship landed on a wooden desk next to some building blocks, magical sparkles around it.", "base_image_path": "/defaults/space-adventures/page-3.png"},
            {"page_number": 4, "text": "As [HERO] touched the rocket, it began to grow bigger and bigger until it filled the whole room! They stepped inside the shiny spaceship and saw buttons of every color. [HERO] took a deep breath, pressed the big green button, and felt very brave.", "image_prompt": "Child astronaut entering a now full-sized shiny silver rocket ship in their bedroom, the room looks slightly smaller as the ship grows, glowing multicolored control panels inside.", "base_image_path": "/defaults/space-adventures/page-4.png"},
            {"page_number": 5, "text": "Zoom! The rocket flew past the moon and soared into the deep, dark space. [HERO] looked out the window and saw the Earth looking like a beautiful blue and white marble. It was the most amazing thing they had ever seen!", "image_prompt": "Rocket ship flying past a giant, cratered moon with Earth glowing in the distant background, deep blue space filled with colorful nebulae and stars.", "base_image_path": "/defaults/space-adventures/page-5.png"},
            {"page_number": 6, "text": "They landed softly on a planet made entirely of pink cotton candy and purple chocolate. [HERO] stepped onto the bouncy ground and realized they were the greatest explorer in the whole universe. The air smelled like sweet strawberries and magic.", "image_prompt": "Child astronaut walking on a pink fluffy planet surface with purple chocolate-like trees, the sky is a soft orange, whimsical and sweet-looking world.", "base_image_path": "/defaults/space-adventures/page-6.png"},
            {"page_number": 7, "text": "Walking further, [HERO] met a group of friendly aliens with three eyes and wobbly antennae. They were playing a game of space-ball with a glowing sphere. 'Would you like to play?' they asked with a cheerful whistle.", "image_prompt": "Child astronaut playing with cute, colorful three-eyed aliens on the cotton candy planet, they are tossing a glowing ball, friendly and happy atmosphere.", "base_image_path": "/defaults/space-adventures/page-7.png"},
            {"page_number": 8, "text": "The aliens showed [HERO] their secret garden where star-flowers grew and sang beautiful songs. Each flower glowed with a different light, and the music made [HERO] feel very happy. They decided to share some stories about Earth with their new friends.", "image_prompt": "A magical garden on the alien planet with glowing, bell-shaped flowers, child astronaut and aliens sitting together, sharing stories, peaceful and musical mood.", "base_image_path": "/defaults/space-adventures/page-8.png"},
            {"page_number": 9, "text": "Suddenly, the ground began to shake, and a giant shadow fell over the garden. A big, friendly space-whale was swimming through the cosmic clouds above! It let out a deep, echoing boom that sounded like a giant hello.", "image_prompt": "A giant, gentle blue space-whale swimming through purple and pink nebula clouds above the alien garden, child and aliens looking up in awe.", "base_image_path": "/defaults/space-adventures/page-9.png"},
            {"page_number": 10, "text": "The space-whale gave [HERO] a ride across the rings of Saturn. They slid down the icy rings like a giant slide, laughing and shouting with joy. The stars felt so close that [HERO] could almost touch them.", "image_prompt": "Child astronaut and one alien friend riding on the back of the giant space-whale as it swims through the bright, icy rings of a giant planet, stars all around.", "base_image_path": "/defaults/space-adventures/page-10.png"},
            {"page_number": 11, "text": "As the sun began to rise over the galaxy, it was time for [HERO] to head home. They said goodbye to their new friends and flew back to their bedroom. [HERO] tucked themselves into bed, knowing that the stars were now their best friends.", "image_prompt": "Child astronaut back in their bedroom, tucked into bed with a toy rocket, looking out at the morning sun and a few fading stars, smiling happily.", "base_image_path": "/defaults/space-adventures/page-11.png"}
        ]
    },
    {
        "id": "jungle-explorer",
        "title": "The Jungle Explorer",
        "description": "Discover hidden treasures in the deep, green jungle!",
        "age_group": "3-6",
        "emoji": "🌳",
        "color": "#059669",
        "pages": [
            {"page_number": 1, "text": "The Jungle Explorer", "image_prompt": "A beautiful book cover: a lush, vibrant jungle with a hidden path. A brave child explorer wearing a safari hat is peeking through giant tropical leaves. Exotic birds fly above. The title 'The Jungle Explorer' is written in playful green vine letters.", "base_image_path": "/defaults/jungle-explorer/page-1.png"},
            {"page_number": 2, "text": "[HERO] put on their lucky safari hat and grabbed a sturdy magnifying glass. The jungle was full of mysteries and every leaf seemed to hide a secret! They could hear the birds singing and the wind whistling through the tall, green trees.", "image_prompt": "Cute child in a safari outfit and hat, holding a magnifying glass, standing at the edge of a lush, vibrant green jungle with colorful tropical flowers.", "base_image_path": "/defaults/jungle-explorer/page-2.png"},
            {"page_number": 3, "text": "Suddenly, a giant parrot with rainbow-colored feathers landed on a branch nearby. 'Follow me, brave explorer!' it chirped with a wink. [HERO] giggled and started to follow the beautiful bird deeper into the heart of the jungle.", "image_prompt": "A large, magnificent parrot with bright red, blue, and yellow feathers perched on a tropical branch, looking back at the child who is following with a smile.", "base_image_path": "/defaults/jungle-explorer/page-3.png"},
            {"page_number": 4, "text": "They came to a wide, sparkling river where a group of friendly monkeys were swinging from vine to vine. One monkey reached out a hand and helped [HERO] swing safely across the water. It was就像 flying through wait-a-minute vines!", "image_prompt": "Child and a group of playful monkeys swinging on thick vines over a clear blue river, tropical forest background with sunlight filtering through leaves.", "base_image_path": "/defaults/jungle-explorer/page-4.png"},
            {"page_number": 5, "text": "On the other side, they found a path hidden behind a giant waterfall. [HERO] walked through the cool mist and discovered a hidden cave that glowed with a golden light. What could be inside this mysterious place?", "image_prompt": "Child walking through the mist of a beautiful jungle waterfall into a cave entrance that is glowing with a soft, inviting golden light, tropical greenery around.", "base_image_path": "/defaults/jungle-explorer/page-5.png"},
            {"page_number": 6, "text": "Inside the cave, [HERO] found a pile of golden bananas that sparkled like the sun! It was the legendary hidden treasure of the jungle. They took one to share with their monkey friends and felt very proud of their discovery.", "image_prompt": "Child inside a cave filled with glowing, golden-skinned bananas, torches on the walls made of large leaves, the child is holding one golden banana with wonder.", "base_image_path": "/defaults/jungle-explorer/page-6.png"},
            {"page_number": 7, "text": "As they left the cave, a baby leopard appeared from behind some ferns. It had soft spots and big, curious eyes. [HERO] realized the leopard was lost and decided to help it find its way back home to its family.", "image_prompt": "A cute baby leopard with big kitten eyes looking out from behind large jungle leaves, child explorer kneeling down to talk to it, gentle and kind vibe.", "base_image_path": "/defaults/jungle-explorer/page-7.png"},
            {"page_number": 8, "text": "They climbed up a giant tree that reached the very top of the jungle. From way up high, [HERO] could see the whole world! They saw the winding river and the mountains far away. The baby leopard purred happily as they looked at the view.", "image_prompt": "Child and baby leopard sitting on a huge branch high in the canopy, looking out over a vast, beautiful jungle landscape with a sunset in the distance.", "base_image_path": "/defaults/jungle-explorer/page-8.png"},
            {"page_number": 9, "text": "Suddenly, they heard a loud rumble. It was the mama leopard calling for her baby! [HERO] led the little leopard down the tree and back to its family. The mama leopard nudged [HERO] gently as a way of saying thank you.", "image_prompt": "Child leading the baby leopard back to its grateful mama leopard in a clearing filled with wild orchids, the leopards look friendly and happy.", "base_image_path": "/defaults/jungle-explorer/page-9.png"},
            {"page_number": 10, "text": "The jungle animals decided to have a big party to celebrate [HERO]'s bravery. There was fruit, music, and everyone danced together under the giant leaves. [HERO] felt like the king or queen of the jungle as they joined the fun.", "image_prompt": "A festive jungle clearing with monkeys, parrots, and leopards all gathered around the child, there are piles of tropical fruits and everyone looks like they are dancing.", "base_image_path": "/defaults/jungle-explorer/page-10.png"},
            {"page_number": 11, "text": "[HERO] was the bravest explorer ever! After a long day of adventure, they headed back to their campsite for a peaceful sleep. As they closed their eyes, they knew that the jungle would always have more secrets for them to find tomorrow.", "image_prompt": "Child explorer in a cozy tent in the jungle, moonlight reflecting off the leaves outside, their safari hat resting nearby, sleeping with a happy smile.", "base_image_path": "/defaults/jungle-explorer/page-11.png"}
        ]
    },
    {
        "id": "under-the-sea",
        "title": "Ocean Explorer",
        "description": "Dive deep into the blue ocean and talk to whales!",
        "age_group": "4-7",
        "emoji": "🐬",
        "color": "#0ea5e9",
        "pages": [
            {"page_number": 1, "text": "Ocean Explorer", "image_prompt": "A magical book cover: a sparkling blue ocean with colorful fish and an old sunken ship. A child in a snorkel mask is waving alongside a giant friendly whale. The title 'Ocean Explorer' is written in wavy water-texture letters.", "base_image_path": "/defaults/under-the-sea/page-1.png"},
            {"page_number": 2, "text": "[HERO] put on their bright yellow snorkel and stepped into the warm, blue water. The ocean was so clear that they could see all the way to the sandy bottom! A school of tiny, silver fish swam around their ankles, welcoming them to the sea.", "image_prompt": "Cute child in a bathing suit and yellow snorkel mask, waist-deep in clear turquoise ocean water, little silver fish swimming around them, sunny beach day.", "base_image_path": "/defaults/under-the-sea/page-2.png"},
            {"page_number": 3, "text": "Suddenly, a giant blue whale with a big, friendly smile swam by. Its voice sounded like a deep, gentle song that filled the whole ocean. The whale gestured with its fin, inviting [HERO] to hop onto its back for a magical ride.", "image_prompt": "A massive, friendly blue whale swimming near the surface, look of invitation, child floating nearby ready to climb on, bubbles and sunlight through the water.", "base_image_path": "/defaults/under-the-sea/page-3.png"},
            {"page_number": 4, "text": "They dove deep under the waves, and [HERO] saw things they had only dreamed of. They passed by a forest of waving green seaweed where tiny seahorses were playing hide and seek. The water felt cool and gentle as they glided through the deep blue.", "image_prompt": "Child riding on the back of the whale, moving through a vibrant underwater forest of tall green seaweed, colorful seahorses peeking out from the leaves.", "base_image_path": "/defaults/under-the-sea/page-4.png"},
            {"page_number": 5, "text": "They discovered a sunken pirate ship resting on the sandy floor, surrounded by colorful coral reefs. [HERO] saw a treasure chest peeking out from behind a wooden door. 'Maybe there are magic pearls inside!' they thought with excitement.", "image_prompt": "An old, wooden sunken pirate ship on the ocean floor, covered in bright pink and orange coral, child and whale swimming alongside it, a glimpse of a treasure chest.", "base_image_path": "/defaults/under-the-sea/page-5.png"},
            {"page_number": 6, "text": "[HERO] swam inside the ship and found a pearl that glowed like the sun! It was protected by a very friendly octopus with eight wiggly arms. The octopus waved hello and handed the pearl to [HERO], who felt like a real ocean hero.", "image_prompt": "Child inside the pirate ship's cabin, holding a large, glowing white pearl, a cute purple octopus is floating next to them, both look happy and magical.", "base_image_path": "/defaults/under-the-sea/page-6.png"},
            {"page_number": 7, "text": "As they emerged from the ship, they were greeted by a pod of playful dolphins. The dolphins did flips and spins in the water, inviting [HERO] to join their dance. It was the most beautiful dance party ever held under the sea!", "image_prompt": "A group of dolphins jumping and playing around the child and the whale in the deep blue ocean, bubbles everywhere, dynamic and joyful scene.", "base_image_path": "/defaults/under-the-sea/page-7.png"},
            {"page_number": 8, "text": "The dolphins led them to a secret underwater city made of glowing shells and shimmering sea-glass. The buildings looked like giant bubbles and the streets were paved with colorful pebbles. [HERO] couldn't believe their eyes!", "image_prompt": "A magical underwater city with buildings shaped like shells and bubbles, glowing in soft blue and green lights, child and sea creatures swimming through the main street.", "base_image_path": "/defaults/under-the-sea/page-8.png"},
            {"page_number": 9, "text": "In the center of the city, there was a fountain that sprayed bubbles of every color. [HERO] caught a bubble and realized it was filled with forgotten stories of the sea. They listened as the bubbles whispered secrets of ancient explorers and magic whales.", "image_prompt": "Child touching a giant, colorful bubble near a shell-shaped fountain in the underwater city, the bubble has faint images inside, magical and mysterious mood.", "base_image_path": "/defaults/under-the-sea/page-9.png"},
            {"page_number": 10, "text": "Suddenly, the ocean sky began to turn to a deep velvet purple, which meant it was time for the moon-tide. The sea creatures gathered to sing a lullaby to the ocean. [HERO] felt very peaceful and loved as they listened to the beautiful song.", "image_prompt": "All the sea creatures (whale, dolphins, octopus) gathered together in the glowing city, the water above is dark purple, peaceful and serene atmosphere.", "base_image_path": "/defaults/under-the-sea/page-10.png"},
            {"page_number": 11, "text": "[HERO] said goodbye to their new friends and swam back to the shore. As they walked onto the soft sand, they looked back at the ocean and smiled. They knew that the magic pearl would always remind them of their wonderful adventure under the sea.", "image_prompt": "Child back on the sandy beach at sunset, holding the glowing pearl, looking out at the calm ocean waves where a whale's tail is peeking out far away, warm colors.", "base_image_path": "/defaults/under-the-sea/page-11.png"}
        ]
    },
    {
        "id": "dino-pal",
        "title": "Prehistoric Pal",
        "description": "Go back in time and make friends with a baby T-Rex!",
        "age_group": "3-8",
        "emoji": "🦖",
        "color": "#b45309",
        "pages": [
            {"page_number": 1, "text": "Prehistoric Pal", "image_prompt": "A fun book cover: a land of volcanoes and giant ferns. A child is hugging a cute baby green T-Rex. In the background, a long-necked dinosaur is peeking. The title 'Prehistoric Pal' is written in rocky, stone letters.", "base_image_path": "/defaults/dino-pal/page-1.png"},
            {"page_number": 2, "text": "[HERO] found a giant, spotted egg hidden in the tall grass of their backyard. It was as big as a watermelon and felt warm to the touch. [HERO] wondered what could be inside such a mysterious and magical-looking egg.", "image_prompt": "Child in a garden looking at a very large, white egg with blue spots hidden in some tall ferns, soft morning light, curiosity and wonder.", "base_image_path": "/defaults/dino-pal/page-2.png"},
            {"page_number": 3, "text": "Crack! Suddenly, the egg began to wiggle and a tiny green head with big, friendly eyes popped out. A baby T-Rex had hatched! [HERO] smiled and named their new prehistoric friend Rexy, who let out a tiny, cute chirp.", "image_prompt": "A small, cute baby green dinosaur hatching from the egg, looking up at the child who is smiling at it, garden setting, soft and whimsical cartoon style.", "base_image_path": "/defaults/dino-pal/page-3.png"},
            {"page_number": 4, "text": "Rexy was very hungry after hatching. [HERO] ran to the kitchen and brought back a giant, juicy leaf from the old oak tree. Rexy nibbled on the leaf and did a happy little dance, wagging its tiny tail in excitement.", "image_prompt": "Child feeding a large, bright green leaf to the baby dinosaur, the dinosaur is standing on its two back legs, look of happiness and friendship.", "base_image_path": "/defaults/dino-pal/page-4.png"},
            {"page_number": 5, "text": "They spent the afternoon playing hide and seek in a forest of tall, ancient ferns that seemed to grow right in [HERO]'s backyard! Rexy was very good at hiding behind the big leaves, but its long tail always gave its position away.", "image_prompt": "Child hiding behind a giant fern leaf, looking for the baby dinosaur whose tail is sticking out from another bush, primeval garden look with huge plants.", "base_image_path": "/defaults/dino-pal/page-5.png"},
            {"page_number": 6, "text": "While they were playing, they found a path that led to a valley filled with giant volcanoes and friendly plant-eating dinosaurs. Everything was so big and colorful! [HERO] and Rexy walked together, exploring this wonderful New World.", "image_prompt": "Child and baby dinosaur walking into a vast valley with steaming volcanoes in the distance and larger, gentle dinosaurs grazing, bright and prehistoric colors.", "base_image_path": "/defaults/dino-pal/page-6.png"},
            {"page_number": 7, "text": "They met a group of Triceratops who were building a nest out of soft moss and colorful flowers. One of them invited [HERO] to help, and they worked together to make the nest extra cozy for the new dinosaur babies.", "image_prompt": "Child and baby dinosaur helping a friendly Triceratops arrange moss and flowers in a nest, other dinosaurs in the background, cooperation and kindness.", "base_image_path": "/defaults/dino-pal/page-7.png"},
            {"page_number": 8, "text": "As it started to rain, they found shelter under the neck of a giant, gentle Brachiosaurus. The rain made the whole world smell fresh and clean, and the Brachiosaurus told them stories of when the Earth was just a baby.", "image_prompt": "Child and Rexy sitting under the long neck of a very tall, gentle dinosaur while it rains, the scene is lush and green, peaceful and protective atmosphere.", "base_image_path": "/defaults/dino-pal/page-8.png"},
            {"page_number": 9, "text": "Suddenly, they saw a group of flying Pterodactyls soaring through the sky! One of them swooped down and gave [HERO] and Rexy a ride high above the clouds. They could see everything from way up there, even the sleeping volcanoes.", "image_prompt": "Child and baby dinosaur riding on the back of a large flying dinosaur, soaring over a prehistoric landscape with waterfalls and forests, epic and exciting.", "base_image_path": "/defaults/dino-pal/page-9.png"},
            {"page_number": 10, "text": "They landed at a sparkling lake where the water was filled with colorful glowing fish. They had a big prehistoric picnic with berries and leaves, sharing stories and laughter. [HERO] realized that even though Rexy was a dinosaur, they were the best of friends.", "image_prompt": "Picnic scene by a beautiful lake with glowing water, child and baby dinosaur sharing berries, other friendly dinosaurs nearby, sunset starting to glow.", "base_image_path": "/defaults/dino-pal/page-10.png"},
            {"page_number": 11, "text": "As the sun set, it was time to head home. Rexy gave [HERO] a big, scaly hug and promised to visit every day. [HERO] went to bed feeling very lucky to have a prehistoric pal. They knew that with Rexy around, every day would be a giant adventure!", "image_prompt": "Child and baby dinosaur hugging in the garden at twilight, the prehistoric valley is visible in the clouds behind them, warm and loving mood.", "base_image_path": "/defaults/dino-pal/page-11.png"}
        ]
    },
    {
        "id": "superhero-academy",
        "title": "Super Hero Power",
        "description": "Learn to fly and save the city with your new powers!",
        "age_group": "6-10",
        "emoji": "🦸",
        "color": "#dc2626",
        "pages": [
            {"page_number": 1, "text": "Super Hero Power", "image_prompt": "A heroic book cover: a modern city skyline at sunset. A child in a red cape is flying high above the buildings, strike an epic pose. The title 'Super Hero Power' is written in bold, comic-book style letters with a yellow glow.", "base_image_path": "/defaults/superhero-academy/page-1.png"},
            {"page_number": 2, "text": "[HERO] found a mysterious red cape hidden in an old chest in the attic. As soon as they put it on, they felt a strange tingle and realized they could jump higher than ever before! They were no longer an ordinary kid; they were a superhero!", "image_prompt": "Child in an attic room, wearing a shiny red cape, jumping very high in the air, looks surprised and excited, dynamic comic book style.", "base_image_path": "/defaults/superhero-academy/page-2.png"},
            {"page_number": 3, "text": "Wait! A loud 'meow' came from the top of the tall city clock tower. A tiny kitten was stuck way up high and couldn't get down! [HERO] took a deep breath, focused their energy, and suddenly they were flying through the sky to help.", "image_prompt": "Child superhero flying towards a very tall clock tower in a vibrant city, a small kitten is perched on the clock hand, blue sky and white clouds.", "base_image_path": "/defaults/superhero-academy/page-3.png"},
            {"page_number": 4, "text": "The kitten was safe in [HERO]'s arms! They landed gently on the ground where the townspeople were cheering and clapping. 'Thank you, Super [HERO]!' they shouted. [HERO] felt very proud to have used their powers for good.", "image_prompt": "Child hero landing on a city street, holding a cute kitten, a group of happy townspeople cheering around them, colorful city buildings, victory atmosphere.", "base_image_path": "/defaults/superhero-academy/page-4.png"},
            {"page_number": 5, "text": "Suddenly, a giant ice cream monster appeared in the middle of the park! It was made of ten different flavors and was accidentally freezing all the swings. [HERO] knew they had to act fast to save the park and all the playtime!", "image_prompt": "A large, colorful blob monster made of melting scoops of ice cream, freezing the playground equipment, child hero standing in front of it ready for action.", "base_image_path": "/defaults/superhero-academy/page-5.png"},
            {"page_number": 6, "text": "[HERO] used their special 'Sun-Beam' power to warm up the park and turn the monster back into regular ice cream. Everyone had a giant ice cream party! It was a very sweet victory for our favorite superhero.", "image_prompt": "Child hero pointing their hands towards the ice cream monster, glowing with a warm yellow light, the monster is melting into a puddle of sprinkles and sauce, kids eating ice cream.", "base_image_path": "/defaults/superhero-academy/page-6.png"},
            {"page_number": 7, "text": "But the day wasn't over yet! A group of runaway balloons was carrying a local puppy high into the air. [HERO] zoomed up like a rocket and caught the balloons, gently bringing the puppy back to its owner with a wagging tail.", "image_prompt": "Child hero flying high in the air, grabbing a bunch of colorful balloons that are tied to a small puppy's harness, sunset city in the background.", "base_image_path": "/defaults/superhero-academy/page-7.png"},
            {"page_number": 8, "text": "Next, [HERO] noticed that the city's fountain had stopped working. Using their super-strength, they cleared a blockage of giant rubber ducks and the water started spraying again, even higher than before! The sparkle was back in the city square.", "image_prompt": "Child hero lifting a giant rubber duck out of a big marble fountain, water starting to spray in a beautiful rainbow arc, people watching with delight.", "base_image_path": "/defaults/superhero-academy/page-8.png"},
            {"page_number": 9, "text": "The Mayor of the city invited [HERO] to the town hall to give them a special golden key. 'You are our greatest protector!' the Mayor said. [HERO] realized that being a hero wasn't just about powers, but about helping everyone in the city.", "image_prompt": "Child hero in their red cape being handed a large golden key by a friendly Mayor, inside a grand hall with flags and decorations, ceremony atmosphere.", "base_image_path": "/defaults/superhero-academy/page-9.png"},
            {"page_number": 10, "text": "As night fell, [HERO] patrolled the city from a high rooftop, watching over all the sleeping children. The city lights twinkled like stars below them. They felt strong, brave, and ready for whatever challenge would come tomorrow.", "image_prompt": "Child hero standing on a skyscraper rooftop at night, cape fluttering in the wind, city lights glowing below, heroic and contemplative pose.", "base_image_path": "/defaults/superhero-academy/page-10.png"},
            {"page_number": 11, "text": "[HERO] took off their cape and tucked it under their pillow, heading to bed for a well-deserved rest. As they fell asleep, they knew that even without the cape, they were a hero at heart. They couldn't wait for another day of saving the world!", "image_prompt": "Child in pajamas, tucking the red cape under their pillow, sleeping with a happy and confident smile, moonlight through the window.", "base_image_path": "/defaults/superhero-academy/page-11.png"}
        ]
    },
    {
        "id": "fairy-tale-castle",
        "title": "The Magic Castle",
        "description": "Help a friendly dragon find its missing crown!",
        "age_group": "4-9",
        "emoji": "🏰",
        "color": "#d946ef",
        "pages": [
            {"page_number": 1, "text": "The Magic Castle", "image_prompt": "A magical book cover: a glowing white castle with purple towers under a starry sky. A child is talking to a polite frog on a velvet pillow. A dragon is peeking from a tower. The title 'The Magic Castle' is written in elegant, princess-style letters with sparkles.", "base_image_path": "/defaults/fairy-tale-castle/page-1.png"},
            {"page_number": 2, "text": "[HERO] walked through the giant golden gates and saw a castle that reached into the clouds. It was made of white stone and had towers that sparkled with fairy dust. [HERO] knew that inside these walls, anything was possible!", "image_prompt": "Child standing in front of a majestic white castle with glowing pink and purple towers, golden gates are open, sparkles and magic in the air, fantasy style.", "base_image_path": "/defaults/fairy-tale-castle/page-2.png"},
            {"page_number": 3, "text": "Inside the grand hall, [HERO] met a very polite green frog wearing a tiny, silver crown. 'Excuse me,' the frog said with a bow. 'The king's magic crown is missing, and we need a brave hero to help us find it before the royal ball!'", "image_prompt": "Child talking to a small, green frog sitting on a velvet pillow, the frog is wearing a little crown and looking hopeful, grand castle interior with high arches.", "base_image_path": "/defaults/fairy-tale-castle/page-3.png"},
            {"page_number": 4, "text": "They went to the magic library where books didn't just sit on shelves—they flew through the air like birds! [HERO] looked through the flying pages and found a clue that pointed towards the high dragon tower.", "image_prompt": "Child in a vast library with books flying around with wings, the room is filled with glowing candles and magical scrolls, search and discovery mood.", "base_image_path": "/defaults/fairy-tale-castle/page-4.png"},
            {"page_number": 5, "text": "As they climbed the winding stairs, they found a room filled with talking mirrors that showed them different parts of the castle. One mirror showed a glimpse of something shiny hidden under a velvet chair in the dragon's playroom.", "image_prompt": "Child standing in a hallway lined with large, ornate mirrors that have moving images inside them, the child is looking closely at one mirror, mystery and magic.", "base_image_path": "/defaults/fairy-tale-castle/page-5.png"},
            {"page_number": 6, "text": "[HERO] found a friendly, sneezing dragon in the playroom who had accidentally used the crown as a toy for its baby dragon eggs. The dragon was very sorry and helped [HERO] pick up the crown, which was covered in dragon glitter.", "image_prompt": "A cute, large green dragon with a baby dragon egg, the child is finding a sparkling golden crown under a chair, the room is filled with dragon toys and glitter.", "base_image_path": "/defaults/fairy-tale-castle/page-6.png"},
            {"page_number": 7, "text": "To thank [HERO], the dragon gave them a ride through the castle's secret gardens. They saw flowers that changed color when you sang to them and trees that grew delicious, magical tea-cakes. It was a feast for the eyes and the tummy!", "image_prompt": "Child riding on the back of the friendly dragon over an enchanted garden with glowing, color-changing flowers and cupcake-filled trees, whimsical and sweet.", "base_image_path": "/defaults/fairy-tale-castle/page-7.png"},
            {"page_number": 8, "text": "Suddenly, they came across a bridge guarded by a group of tiny, dancing gnomes. To cross, [HERO] had to show them their best dance move! [HERO] did a silly spin, and the gnomes cheered and let them through with a laugh.", "image_prompt": "Child dancing in front of a group of small, colorful gnomes on a stone bridge, the gnomes are playing tiny instruments, fun and joyful atmosphere.", "base_image_path": "/defaults/fairy-tale-castle/page-8.png"},
            {"page_number": 9, "text": "They returned the crown to the King and Queen just in time for the Royal Ball. The whole castle erupted in cheers, and [HERO] was invited to be the guest of honor. They wore a special silver medal and felt like royalty.", "image_prompt": "Child handing the golden crown to the King and Queen in a grand ballroom, people in beautiful costumes are cheering, festive and royal celebration.", "base_image_path": "/defaults/fairy-tale-castle/page-9.png"},
            {"page_number": 10, "text": "The ball lasted all night, with music that sounded like tinkling bells and dancing that felt like floating on clouds. [HERO] danced with the frog and the dragon, making memories that they would never, ever forget.", "image_prompt": "Child dancing in the ballroom with the green frog and the friendly dragon, glowing lights and beautiful decorations everywhere, joyful and magical night.", "base_image_path": "/defaults/fairy-tale-castle/page-10.png"},
            {"page_number": 11, "text": "As the moon began to set, [HERO] walked back through the golden gates. The castle faded into a soft glow behind them. They knew that whenever they closed their eyes, they could visit the magic castle and their new friends once again.", "image_prompt": "Child walking away from the glowing castle at dawn, looking back with a wave, the castle is fading into a magical mist, peaceful and sentimental mood.", "base_image_path": "/defaults/fairy-tale-castle/page-11.png"}
        ]
    },
    {
        "id": "future-city",
        "title": "Robot Best Friend",
        "description": "Build your own robot and fly through a neon city!",
        "age_group": "7-12",
        "emoji": "🤖",
        "color": "#6366f1",
        "pages": [
            {"page_number": 1, "text": "Robot Best Friend", "image_prompt": "A futuristic book cover: a city of neon lights and hover-cars. A child is high-fiving a cute white robot with glowing blue eyes. The title 'Robot Best Friend' is written in digital, neon-blue letters with a techy look.", "base_image_path": "/defaults/future-city/page-1.png"},
            {"page_number": 2, "text": "[HERO] sat in their high-tech lab, surrounded by glowing screens and buzzing tools. After months of hard work, they finally fixed the last wire on their new creation. Suddenly, the robot's eyes turned bright blue and it let out a friendly 'beep!'", "image_prompt": "Child in a futuristic lab with neon lights and holograms, working on a cute, white and blue robot, the robot's eyes are glowing, high-tech and exciting.", "base_image_path": "/defaults/future-city/page-2.png"},
            {"page_number": 3, "text": "'Hello, [HERO]! I am ready for our first mission!' said the robot in a cheerful voice. Its name was Beep-Boop, and it had a built-in map and a special compartment for storing snacks. [HERO] was so excited to have a robot best friend.", "image_prompt": "The robot, Beep-Boop, is waving its mechanical hand at the child, the child is smiling and high-fiving the robot, lab setting with gadgets around.", "base_image_path": "/defaults/future-city/page-3.png"},
            {"page_number": 4, "text": "They hopped onto a hover-scooter and zoomed out of the lab, soaring into the neon lights of the Future City. Buildings weren't made of brick, but of glass and light, and cars flew through the air like colorful shooting stars.", "image_prompt": "Child and robot on a sleek, glowing hover-scooter, flying through a city with skyscrapers of light and neon signs, blue and purple color palette, dynamic motion.", "base_image_path": "/defaults/future-city/page-4.png"},
            {"page_number": 5, "text": "Their first stop was the Moon-Mall, a giant shopping center floating high in the sky. Beep-Boop helped [HERO] pick out a pair of gravity-boots that allowed them to walk on the walls and ceiling just like a space-cat!", "image_prompt": "Child and robot inside a futuristic shopping mall, the child is walking on the ceiling with glowing boots, shoppers are robots and aliens, fun and surreal.", "base_image_path": "/defaults/future-city/page-5.png"},
            {"page_number": 6, "text": "While at the mall, they noticed a group of robots who were struggling to organize a grand robot-basketball tournament. Beep-Boop used its super-fast brain to create a perfect game schedule, and [HERO] showed them how to do a three-point dunk!", "image_prompt": "Child and robot on a high-tech basketball court, Beep-Boop is projecting a hologram schedule, child is jumping high for a dunk, stadium filled with cheering robots.", "base_image_path": "/defaults/future-city/page-6.png"},
            {"page_number": 7, "text": "After the game, they explored the neon park where the trees were made of fiber-optics and the grass glowed in the dark. They found a group of robotic puppies who were looking for someone to play with, and [HERO] spent the hour throwing digital frisbees.", "image_prompt": "Child and robot in a park with glowing trees and neon grass, playing with small robotic dogs that have screens for faces, playful and vibrant scene.", "base_image_path": "/defaults/future-city/page-7.png"},
            {"page_number": 8, "text": "Suddenly, a giant city-drone got its propellers tangled in some sky-vines. [HERO] used their gravity boots to climb up and Beep-Boop used its laser-tool to gently untangle the drone. The drone let out a happy buzz and flew back to its route.", "image_prompt": "Child hero on the side of a building, untangling a large friendly drone while Beep-Boop helps from the hover-scooter, high-altitude city action.", "base_image_path": "/defaults/future-city/page-8.png"},
            {"page_number": 9, "text": "To celebrate their successful day, they went to a cafe where a robot waiter served them colorful nutrient-shakes that tasted like liquid rainbow and cookies. They talked about all the amazing things they would build together in the future.", "image_prompt": "Child and robot sitting at a futuristic cafe table, drinking glowing shakes from tall glasses, a robot waiter is in the background, neon city lights through the window.", "base_image_path": "/defaults/future-city/page-9.png"},
            {"page_number": 10, "text": "As the sun set over the glowing horizon, they watched the city lights turn even brighter. Beep-Boop projected a beautiful holographic story about the history of robots and humans working together as a team. [HERO] felt very lucky to have such a smart friend.", "image_prompt": "Child and robot sitting on a high balcony overlooking the neon city at night, Beep-Boop is projecting a 3D hologram of a human and robot shaking hands, peaceful mood.", "base_image_path": "/defaults/future-city/page-10.png"},
            {"page_number": 11, "text": "[HERO] and Beep-Boop returned to the lab, exhausted but happy. As [HERO] went to sleep, Beep-Boop plugged itself into its charger and whispered, 'Goodnight, partner.' [HERO] knew that with Beep-Boop, the future would always be bright.", "image_prompt": "Child sleeping in a high-tech bedroom, Beep-Boop is standing nearby in its charging station with its eyes dimmed, moonlight reflecting off the robot's metal skin.", "base_image_path": "/defaults/future-city/page-11.png"}
        ]
    },
    {
        "id": "pirate-adventure",
        "title": "The Brave Pirate",
        "description": "Sail the high seas and find the hidden golden chest!",
        "age_group": "5-10",
        "emoji": "🏴‍☠️",
        "color": "#0f172a",
        "pages": [
            {"page_number": 1, "text": "The Brave Pirate", "image_prompt": "A bold book cover: a wooden pirate ship in a tropical bay. A child pirate with a bandana is looking through a telescope. A parrot is on their shoulder. The title 'The Brave Pirate' is written in weathered parchment letters.", "base_image_path": "/defaults/pirate-adventure/page-1.png"},
            {"page_number": 2, "text": "Captain [HERO] stood on the deck of their mighty ship, the 'Sea-Dragon', and looked through a polished brass telescope. Far on the horizon, they saw the outline of a mysterious island with palm trees that swayed in the tropical breeze.", "image_prompt": "Child in a pirate outfit with a bandana and vest, standing on a wooden ship deck, looking through a telescope at a distant tropical island, bright sunny day, ocean waves.", "base_image_path": "/defaults/pirate-adventure/page-2.png"},
            {"page_number": 3, "text": "'Land ho! Land ho!' shouted Pip the Parrot from [HERO]'s shoulder. With a confident spin of the ship's wheel, Captain [HERO] steered the Sea-Dragon through the crashing waves, heading straight for the hidden beach.", "image_prompt": "Child hero steering a large wooden ship's wheel, a colorful parrot is on their shoulder, waves are splashing against the side of the ship, dynamic and adventurous.", "base_image_path": "/defaults/pirate-adventure/page-3.png"},
            {"page_number": 4, "text": "They landed on the soft, white sand and followed an old, crinkly map that had been passed down through generations of pirates. The map had a big red 'X' marked right next to a giant, ancient palm tree that looked like a hand pointing to the sky.", "image_prompt": "Child pirate on a beach holding a tattered treasure map, looking towards a unique palm tree with a curved trunk, sandy beach with shells and clear water.", "base_image_path": "/defaults/pirate-adventure/page-4.png"},
            {"page_number": 5, "text": "[HERO] grabbed a shiny silver shovel and started to dig under the palm tree. Clink! The shovel hit something hard and wooden. With a lot of effort, they pulled a heavy chest out of the sand. It was locked with a rusty, pirate-shaped keyhole.", "image_prompt": "Child pirate digging in the sand with a shovel, the top of a wooden chest is becoming visible, pirate ship anchored in the bay in the background.", "base_image_path": "/defaults/pirate-adventure/page-5.png"},
            {"page_number": 6, "text": "Captain [HERO] pulled out the secret key they had hidden in their boot and turned it in the lock. The chest creaked open and revealed... not gold, but thousands of sparkling golden chocolate coins! It was the best treasure a pirate could ever find.", "image_prompt": "Child pirate opening the chest which is overflowing with wrapped gold chocolate coins, their eyes are wide with joy, bright beach lighting, tropical setting.", "base_image_path": "/defaults/pirate-adventure/page-6.png"},
            {"page_number": 7, "text": "While they were celebrating, a group of friendly sea turtles emerged from the water. They were looking for a way to get to their secret nesting beach, which was blocked by some fallen coconut trees. [HERO] decided to use their pirate strength to help.", "image_prompt": "Child pirate talking to a group of cute, large sea turtles on the beach, the child is pointing towards some fallen logs, helpful and kind pirate vibe.", "base_image_path": "/defaults/pirate-adventure/page-7.png"},
            {"page_number": 8, "text": "Using some ropes from the ship, [HERO] and their animal crew pulled the logs out of the way. The sea turtles were so happy they invited [HERO] to follow them to the Secret Lagoon, where the water was filled with glowing blue jellyfish.", "image_prompt": "Child pirate and a group of animals (monkey and parrot) pulling a log with a rope, sea turtles watching, tropical forest edge, teamwork and effort.", "base_image_path": "/defaults/pirate-adventure/page-8.png"},
            {"page_number": 9, "text": "The Secret Lagoon was the most beautiful place [HERO] had ever seen. The water felt like warm silk, and the glowing jellyfish looked like floating lanterns under the waves. They spent the afternoon swimming and playing with their new turtle friends.", "image_prompt": "Child swimming in a calm lagoon at twilight with glowing blue jellyfish around them, the scene is magical and serene, coconut trees reflecting in the water.", "base_image_path": "/defaults/pirate-adventure/page-9.png"},
            {"page_number": 10, "text": "As the moon rose, Captain [HERO] hosted a big pirate feast on the beach for all the animals. They shared the chocolate coins and told stories of their daring adventures on the high seas. The sound of the waves felt like a gentle pirate song.", "image_prompt": "A big campfire on the beach, child pirate and many animals (turtles, monkeys, birds) eating and laughing together, the treasure chest is open nearby, starry night.", "base_image_path": "/defaults/pirate-adventure/page-10.png"},
            {"page_number": 11, "text": "Captain [HERO] sailed the Sea-Dragon back towards the horizon, knowing that they were the bravest pirate in the whole world. As they looked at the stars, they knew that there were many more islands and many more treasures waiting to be found.", "image_prompt": "Child pirate standing at the back of the ship, looking at the moonlit ocean and the twinkling stars, the ship is sailing away into the night, peaceful and adventurous.", "base_image_path": "/defaults/pirate-adventure/page-11.png"}
        ]
    }
]

def get_all_templates() -> List[Dict]:
    return BOOK_TEMPLATES

def get_template_by_id(template_id: str) -> Dict:
    return next((t for t in BOOK_TEMPLATES if t["id"] == template_id), None)
